apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-price-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: energy-price-python
  template:
    metadata:
      labels:
        app: energy-price-python
    spec:
      containers:
      - name: python-wsgi-app
        image: python-wsgi-app
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: energy-price-service
spec:
  selector:
    app: energy-price-python # This should match the label of one of the deployments; adjust as needed.
  type: LoadBalancer # Expose the service externally using a cloud provider's load balancer.
  ports:
    - port: 80          # External port to access the service.
      targetPort: 8000  # Port on which the application is running inside the container.
